### ISSUE TITLE
Plugin as download

### ISSUE THREAD

**Issue by vincentschroeder** [ekandreas/bladerunner#39]
thx.

**Comment by vincentschroeder** [comment]
I just found it. To make it more popular, you should upload it to the wp repository.

**Comment by vincentschroeder** [comment]
Any plans to add these handy shortcuts like it was in the wp blade plugin?

    @wpquery($query_args)
    @wpempty
    @wpend

etc.

**Comment by vincentschroeder** [comment]
Not needed anymore. I extracted the syntax from the wp blade plugin and extended these shorthands via add_filter(). Thank you for the great work!

**Comment by ekandreas** [comment]
The plugin is downloadable via http://bladerunner.elseif.se but I will not publish the plugin to the public library because the dependent Laravel components to it. WordPress development without composer support is not recommended. But perhaps you already know that :-)
The old WP Blade does support L4 but not L5-syntax.
Check out Sage templating that is Blade from v9 in beta. https://github.com/roots/sage/blob/master/src/lib/Sage/Template/Blade.php

Happy coding!
